=== juns8522/web_sys_dev_ass/WebContent/WEB-INF/blogs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:simpleType name="date">
  <xs:restriction base="xs:string">
   <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
  </xs:restriction>
 </xs:simpleType>

 <xs:element name="blogs">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="blog" maxOccurs="unbounded">
     <xs:complexType>
      <xs:sequence>
       <xs:element name="email" type="xs:string"/>
       <xs:element name="date" type="date"/>
       <xs:element name="title" type="xs:string"/>
       <xs:element name="body" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:integer"/>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== juns8522/web_sys_dev_ass/WebContent/WEB-INF/blogs.xml
<?xml version="1.0" encoding="UTF-8"?>
<blogs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="blogs.xsd">
 <blog id="1">
  <email>juns@gmail.com</email>
  <date>13/09/2013</date>
  <title>first</title>
  <body>hi.</body>
 </blog>
 <blog id="2">
  <email>ryan@gmail.com</email>
  <date>13/09/2013</date>
  <title>first</title>
  <body>hi. Jun</body>
 </blog>
 <blog id="3">
  <email>juns@gmail.com</email>
  <date>15/09/2013</date>
  <title>second</title>
  <body>hi. Ryan</body>
 </blog>
 <blog id="4">
  <email>ryan@gmail.com</email>
  <date>20/09/2013</date>
  <title>second</title>
  <body>The second article by Ryan</body>
 </blog>
 <blog id="5">
  <email>juns@gmail.com</email>
  <date>30/09/2013</date>
  <title>Third</title>
  <body>This is my second article</body>
 </blog>
 <blog id="6">
  <email>juns@gmail.com</email>
  <date>15/10/2013</date>
  <title>Forth</title>
  <body>Bye Ryan</body>
 </blog>
 <blog id="7">
  <email>ryan@gmail.com</email>
  <date>16/10/2013</date>
  <title>third</title>
  <body>bye. Jun</body>
 </blog>
</blogs>
