=== juns8522/web_sys_dev_ass/WebContent/WEB-INF/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="users">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="user" maxOccurs="unbounded">
     <xs:complexType>
      <xs:sequence>
       <xs:element name="email" type="xs:string"/>
       <xs:element name="password" type="xs:string"/>
       <xs:element name="name" type="xs:string"/>
       <xs:element name="description" type="xs:string"/>
       <xs:element name="friends">
        <xs:complexType>
         <xs:sequence>
          <xs:element name="fEmail" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
        </xs:complexType>
       </xs:element>
       <xs:element name="request">
        <xs:complexType>
         <xs:sequence>
          <xs:element name="rEmail" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
        </xs:complexType>
       </xs:element>
      </xs:sequence>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== juns8522/web_sys_dev_ass/WebContent/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="users.xsd">
 <user>
  <email>juns@gmail.com</email>
  <password>1111</password>
  <name>Jun Lee</name>
  <description>First User</description>
  <friends>
  	<fEmail>ryan@gmail.com</fEmail>
  </friends>
  <request>
    <rEmail>park@gmail.com</rEmail>
  </request>
 </user>
 <user>
  <email>ryan@gmail.com</email>
  <password>1111</password>
  <name>Ryan Heise</name>
  <description>Second User</description>
  <friends>
  	<fEmail>juns@gmail.com</fEmail>
  </friends>
  <request>
    <rEmail>park@gmail.com</rEmail>
  </request>
 </user>
</users>
